# version: "3.8"

services:
  java-server:
    image: grpc-multi-language-java-server
    container_name: java-server
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 5s
      retries: 5
      timeout: 3s

  python-server:
    image: grpc-multi-language-python-server
    container_name: python-server
    ports:
      - "50052:50051"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 5s
      retries: 5
      timeout: 3s

  java-client:
    image: grpc-multi-language-java-client
    container_name: java-client
    depends_on:
      java-server:
        condition: service_healthy
      python-server:
        condition: service_healthy

  python-client:
    image: grpc-multi-language-python-client
    container_name: python-client
    depends_on:
      java-server:
        condition: service_healthy
      python-server:
        condition: service_healthy
